/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domen.Izvestaj;
import domen.Lekar;
import domen.Pacijent;
import domen.ZakazanTermin;
import java.awt.BorderLayout;
import java.awt.Font;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import kontr.Kontroler;
import kontr.PdfGenerator;

/**
 *
 * @author Nemanja
 */
public class FormaPrikazIzvestaja extends javax.swing.JFrame {

    private AutocompleteTextField tfPacijent;
    private Izvestaj i;

    /**
     * Creates new form FormaJedanIzvestaj
     */
    public FormaPrikazIzvestaja(Izvestaj i) {
        initComponents();
        this.i = i;
        popuniComboLekari();
        if (i.getPac() != null) {
            DateTimeFormatter f = DateTimeFormatter.ofPattern("dd.MM.yyyy");
            lblDatum.setText(lblDatum.getText() + " " + i.getDatumVreme().toLocalDate().format(f));
            lblPac1.setText(lblPac1.getText() + i.getPac());
            cmbLekari1.setSelectedItem(i.getLekar());
            
            taAnamneza.setText(i.getAnamneza());
            taDijagnoza.setText(i.getDg());
            taTerapija.setText(i.getTerapija());
            taNalaz.setText(i.getNalaz());
            taKontrola.setText(i.getKontrola());
            taZakljucak.setText(i.getZakljucak());

            btnDodaj.setVisible(false);
            panelPacijent.setVisible(false);
            
        } else {
            tfPacijent = new AutocompleteTextField(Kontroler.getInstance().vratiPacijente(), 20);
            tfPacijent.setFont(new Font("Arial", Font.PLAIN, 20));

            panelPacijent.removeAll();
            panelPacijent.setLayout(new BorderLayout());
            panelPacijent.add(tfPacijent, BorderLayout.CENTER);

            panelPacijent.revalidate();
            panelPacijent.repaint();

            btnIzmeni.setVisible(false);
            lblDatum.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLekar = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblPac1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAnamneza = new javax.swing.JTextArea();
        lblDatum1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDijagnoza = new javax.swing.JTextArea();
        lblDatum2 = new javax.swing.JLabel();
        lblDatum3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taTerapija = new javax.swing.JTextArea();
        btnDodaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbLekari1 = new javax.swing.JComboBox<>();
        panelPacijent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taNalaz = new javax.swing.JTextArea();
        lblDatum4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taKontrola = new javax.swing.JTextArea();
        lblDatum5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taZakljucak = new javax.swing.JTextArea();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 681));

        lblLekar.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblLekar.setText("Lekar:");

        lblDatum.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum.setText("Datum pregleda:");

        lblPac1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblPac1.setText("Pacijent:");

        taAnamneza.setColumns(20);
        taAnamneza.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taAnamneza.setLineWrap(true);
        taAnamneza.setRows(5);
        taAnamneza.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taAnamneza);

        lblDatum1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum1.setText("Anamneza:");

        taDijagnoza.setColumns(20);
        taDijagnoza.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taDijagnoza.setLineWrap(true);
        taDijagnoza.setRows(5);
        taDijagnoza.setWrapStyleWord(true);
        jScrollPane2.setViewportView(taDijagnoza);

        lblDatum2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum2.setText("Dijagnoza:");

        lblDatum3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum3.setText("Terapija:");

        taTerapija.setColumns(20);
        taTerapija.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taTerapija.setLineWrap(true);
        taTerapija.setRows(5);
        taTerapija.setWrapStyleWord(true);
        jScrollPane3.setViewportView(taTerapija);

        btnDodaj.setBackground(new java.awt.Color(0, 51, 153));
        btnDodaj.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(255, 255, 255));
        btnDodaj.setText("Štampaj izveštaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        cmbLekari1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        javax.swing.GroupLayout panelPacijentLayout = new javax.swing.GroupLayout(panelPacijent);
        panelPacijent.setLayout(panelPacijentLayout);
        panelPacijentLayout.setHorizontalGroup(
            panelPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        panelPacijentLayout.setVerticalGroup(
            panelPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Klinički nalaz:");

        taNalaz.setColumns(20);
        taNalaz.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taNalaz.setLineWrap(true);
        taNalaz.setRows(5);
        taNalaz.setWrapStyleWord(true);
        jScrollPane4.setViewportView(taNalaz);

        lblDatum4.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum4.setText("Kontrola:");

        taKontrola.setColumns(20);
        taKontrola.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taKontrola.setLineWrap(true);
        taKontrola.setRows(5);
        taKontrola.setWrapStyleWord(true);
        jScrollPane5.setViewportView(taKontrola);

        lblDatum5.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum5.setText("Zaključak:");

        taZakljucak.setColumns(20);
        taZakljucak.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taZakljucak.setLineWrap(true);
        taZakljucak.setRows(5);
        taZakljucak.setWrapStyleWord(true);
        jScrollPane6.setViewportView(taZakljucak);

        btnIzmeni.setBackground(new java.awt.Color(0, 51, 153));
        btnIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Izmeni izveštaj");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatum1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbLekari1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(172, 172, 172)
                        .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(399, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblPac1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                                .addComponent(panelPacijent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDatum2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDatum3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDatum4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDatum5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekar)
                    .addComponent(cmbLekari1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPac1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(lblDatum1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDatum2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblDatum3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblDatum4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblDatum5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDodaj)
                            .addComponent(btnIzmeni))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if(tfPacijent.getSelectedPacijent()!=null) i.setPac(tfPacijent.getSelectedPacijent());
        else{
            Pacijent neu = new Pacijent(0, tfPacijent.getText(), LocalDate.MIN, "0");
            neu.setSifraPac((int) Kontroler.getInstance().dodajPacijent(neu));
            System.out.println(neu.getSifraPac()); // ispise se kako treba, ne bude 0
            i.setPac(neu);
            System.out.println(i.getPac().getSifraPac());
        }
        i.setDatumVreme(LocalDateTime.now());
        i.setLekar((Lekar) cmbLekari1.getSelectedItem());
        i.setAnamneza(taAnamneza.getText());
        i.setDg(taDijagnoza.getText());
        i.setTerapija(taTerapija.getText());
        i.setNalaz(taNalaz.getText());
        i.setKontrola(taKontrola.getText());
        i.setZakljucak(taZakljucak.getText());
        System.out.println("Id pac izv:"+i.getPac().getSifraPac());
        Kontroler.getInstance().dodajIzvestaj(i);
        PdfGenerator.exportIzvestaj(i);
        this.dispose();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        i.setAnamneza(taAnamneza.getText());
        i.setDg(taDijagnoza.getText());
        i.setTerapija(taTerapija.getText());
        i.setNalaz(taNalaz.getText());
        i.setKontrola(taKontrola.getText());
        i.setZakljucak(taZakljucak.getText());
        Kontroler.getInstance().izmeniIzvestaj(i);
        PdfGenerator.exportIzvestaj(i);
        this.dispose();
    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox<Lekar> cmbLekari1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatum1;
    private javax.swing.JLabel lblDatum2;
    private javax.swing.JLabel lblDatum3;
    private javax.swing.JLabel lblDatum4;
    private javax.swing.JLabel lblDatum5;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblPac1;
    private javax.swing.JPanel panelPacijent;
    private javax.swing.JTextArea taAnamneza;
    private javax.swing.JTextArea taDijagnoza;
    private javax.swing.JTextArea taKontrola;
    private javax.swing.JTextArea taNalaz;
    private javax.swing.JTextArea taTerapija;
    private javax.swing.JTextArea taZakljucak;
    // End of variables declaration//GEN-END:variables
        private void popuniComboLekari() {
        List<Lekar> ls = Kontroler.getInstance().vratiLekare();
        for (Lekar l : ls) {
            cmbLekari1.addItem(l);
        }
    }
}
