/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domen.Izvestaj;
import domen.Lekar;
import domen.Pacijent;
import java.awt.BorderLayout;
import java.awt.Font;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import kontr.Kontroler;
import kontr.PdfGenerator;

/**
 *
 * @author darko
 */
public class FormaBlankoIzvestaj extends javax.swing.JFrame {

    private AutocompleteTextField tfPacijent;
    private Izvestaj i;

    /**
     * Creates new form FormaBlankoIzvestaj
     */
    public FormaBlankoIzvestaj(Izvestaj i) {
        initComponents();
        this.i = i;
        popuniComboLekari();
        tfPacijent = new AutocompleteTextField(Kontroler.getInstance().vratiPacijente(), 20);
        tfPacijent.setFont(new Font("Arial", Font.PLAIN, 20));

        panelPacijent.removeAll();
        panelPacijent.setLayout(new BorderLayout());
        panelPacijent.add(tfPacijent, BorderLayout.CENTER);

        panelPacijent.revalidate();
        panelPacijent.repaint();
        if (i.getPac() != null) {
            DateTimeFormatter f = DateTimeFormatter.ofPattern("dd.MM.yyyy");
            lblDatum.setText(lblDatum.getText() + " " + i.getDatumVreme().toLocalDate().format(f));
            tfPacijent.setText(i.getPac().getImePrez());
            cmbLekari1.setSelectedItem(i.getLekar());
            taIzvestaj.setText(i.getAnamneza());

            btnDodaj.setVisible(false);
        } else {
            btnIzmeni.setVisible(false);
            lblDatum.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLekar = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblPac1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taIzvestaj = new javax.swing.JTextArea();
        btnDodaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbLekari1 = new javax.swing.JComboBox<>();
        panelPacijent = new javax.swing.JPanel();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 681));

        lblLekar.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblLekar.setText("Lekar:");

        lblDatum.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblDatum.setText("Datum pregleda:");

        lblPac1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblPac1.setText("Pacijent:");

        taIzvestaj.setColumns(20);
        taIzvestaj.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        taIzvestaj.setLineWrap(true);
        taIzvestaj.setRows(5);
        taIzvestaj.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taIzvestaj);

        btnDodaj.setBackground(new java.awt.Color(0, 51, 153));
        btnDodaj.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(255, 255, 255));
        btnDodaj.setText("Štampaj izveštaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        cmbLekari1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        javax.swing.GroupLayout panelPacijentLayout = new javax.swing.GroupLayout(panelPacijent);
        panelPacijent.setLayout(panelPacijentLayout);
        panelPacijentLayout.setHorizontalGroup(
            panelPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        panelPacijentLayout.setVerticalGroup(
            panelPacijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        btnIzmeni.setBackground(new java.awt.Color(0, 51, 153));
        btnIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Izmeni izveštaj");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(436, 436, 436)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelPacijent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPac1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbLekari1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)
                                .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekar)
                    .addComponent(cmbLekari1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPac1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnIzmeni))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if (tfPacijent.getSelectedPacijent() != null) {
            i.setPac(tfPacijent.getSelectedPacijent());
        } else {
            Pacijent neu = new Pacijent(0, tfPacijent.getText(), LocalDate.MIN, "0");
            neu.setSifraPac((int) Kontroler.getInstance().dodajPacijent(neu));
            i.setPac(neu);
            System.out.println(i.getPac().getSifraPac());
        }
        i.setDatumVreme(LocalDateTime.now());
        i.setLekar((Lekar) cmbLekari1.getSelectedItem());
        i.setAnamneza(taIzvestaj.getText());
        Kontroler.getInstance().dodajIzvestaj(i);
        PdfGenerator.exportIzvestaj(i);
        this.dispose();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        if (tfPacijent.getSelectedPacijent() != null) {
            i.setPac(tfPacijent.getSelectedPacijent());
        } else {
            Pacijent neu = new Pacijent(0, tfPacijent.getText(), LocalDate.MIN, "0");
            neu.setSifraPac((int) Kontroler.getInstance().dodajPacijent(neu));
            i.setPac(neu);
            System.out.println(i.getPac().getSifraPac());
        }
        i.setLekar((Lekar) cmbLekari1.getSelectedItem());
        i.setAnamneza(taIzvestaj.getText());
        Kontroler.getInstance().izmeniIzvestaj(i);
        PdfGenerator.exportIzvestaj(i);
        this.dispose();
    }//GEN-LAST:event_btnIzmeniActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JComboBox<Lekar> cmbLekari1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblPac1;
    private javax.swing.JPanel panelPacijent;
    private javax.swing.JTextArea taIzvestaj;
    // End of variables declaration//GEN-END:variables
        private void popuniComboLekari() {
        List<Lekar> ls = Kontroler.getInstance().vratiLekare();
        for (Lekar l : ls) {
            cmbLekari1.addItem(l);
        }
    }
}
